'use server';

import { fetchClient } from "@/lib/fetchClient";
import { cookies } from "next/headers";

export async function generateReportAction() {
  const cookieStore = await cookies();
  const token = cookieStore.get("token")?.value;

  try {
    // 1. Fetch Incidents
    const incidents = await fetchClient<any[]>("/api/incidents", {
      method: "GET",
      headers: token ? { 'Authorization': `Bearer ${token}` } : {},
      cache: "no-store"
    });

    // 2. Calculate Metrics (Mock AI Logic)
    const totalIncidents = incidents.length;
    const incidentCounts: Record<string, number> = {};
    let totalDelays = 0;

    incidents.forEach(inc => {
        incidentCounts[inc.incident_type] = (incidentCounts[inc.incident_type] || 0) + 1;
        if (inc.incident_type === 'DELAY' || inc.incident_type === 'CONGESTION') {
            totalDelays++;
        }
    });

    const mostCommonType = Object.entries(incidentCounts).sort((a, b) => b[1] - a[1])[0]?.[0] || "None";
    
    // Random estimated value lost (Mock)
    const valueLost = Math.floor(Math.random() * 500000) + 100000; 

    // 3. Generate "Sophisticated" Report
    const report = `
# Kwara State Logistics Daily Briefing
**Date:** ${new Date().toLocaleDateString()}
**Classification:** INTERNAL USE ONLY

## Executive Summary
Logistics operations across the state have maintained **${totalDelays > 5 ? 'MODERATE' : 'HIGH'}** efficiency over the last 24 hours. However, localized disruptions have been detected in key transit corridors.

## Section 1: Critical Alerts
*   **Total Incidents Recorded:** ${totalIncidents}
*   **Primary Disruption Vector:** ${mostCommonType}
*   **Congestion Analysis:** ${totalDelays} significant delay events detected.
    *   *Observation:* High traffic density reported near Oja Oba market axis.
    *   *Observation:* Minor breakdown reported on Ilorin-Jebba road.

## Section 2: Economic Impact Assessment
Preliminary analysis suggests a potential risk to perishable cargo.
*   **Estimated Value at Risk:** ₦${valueLost.toLocaleString()}
*   **Affected Commodities:** Tomatoes, Yams, and Cassava.

## Section 3: Strategic Recommendations
1.  **Route Optimization:** Divert heavy trucks from Oja Oba during peak market hours (10:00 AM - 2:00 PM).
2.  **Infrastructure:** Deploy rapid response towing units to Ilorin-Jebba road to minimize breakdown-induced delays.
3.  **Driver Advisory:** Issue immediate alerts to all drivers regarding the congestion zones.

---
*Generated by Agri-Track AI Intelligence Node*
    `;

    return { success: true, report };

  } catch (error: any) {
    console.error("Failed to generate report:", error);
    return { success: false, error: "Failed to generate report" };
  }
}
